#ifndef PRMEMC_H
#define PRMEMC_H

#include "Constants.hh"
#include "TrackletCalculator.hh"
#include "ProjectionRouter.hh"
#include "MatchEngine.h"
#include "MatchCalculator.hh"

void PRMEMC(
BXType bx,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L1L2E_L3PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L4PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L4PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L4PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L5PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L5PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L6PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2E_L6PHIC,
const AllStubMemory<BARREL2S>& AS_L6PHIBn4,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L6PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L6PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L6PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4C_L6PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2B_L6PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2B_L6PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC20n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L6PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB15n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2J_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4C_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2H_L4PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4E_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L6PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB16n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6A_L4PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2G_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2H_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2I_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2J_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2K_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2L_L6PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA2n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4B_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4C_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4D_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4E_L6PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB11n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4F_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6C_L4PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4G_L6PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4H_L6PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC24n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB12n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA7n1,
const AllStubMemory<BARREL2S>& AS_L5PHIAn2,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L1L2F_L3PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4D_L6PHIA,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB13n1,
const AllStubMemory<BARREL2S>& AS_L5PHIBn3,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2G_L4PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA8n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA3n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA4n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA5n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA5n1,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB9n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2I_L4PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA6n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC21n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA7n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB16n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA8n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB9n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA1n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB10n1,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L1L2G_L3PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB11n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB12n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB12n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA1n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB13n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA2n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB14n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2G_L6PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB15n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L4PHIA,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIB16n1,
const AllStubMemory<BARREL2S>& AS_L4PHIAn3,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC17n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6C_L4PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC18n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC19n1,
const AllStubMemory<BARRELPS>& AS_L3PHIBn4,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC20n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2I_L6PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC21n1,
const AllStubMemory<BARREL2S>& AS_L4PHIBn5,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2J_L4PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6A_L4PHIA,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC22n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB13n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC23n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA8n1,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB14n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIC24n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2B_L4PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4B_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L4PHIB,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB15n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC18n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB9n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA4n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4D_L6PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA5n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2H_L5PHIB,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB10n1,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB16n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA2n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC22n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2G_L4PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC17n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4F_L6PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L4PHIC,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L5L6B_L3PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2H_L4PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2K_L4PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC18n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6B_L4PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA3n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6D_L4PHIC,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC17n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB13n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC20n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2B_L5PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L5PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L5PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2B_L5PHIB,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L1L2C_L3PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC19n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L5PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB14n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4D_L5PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4E_L5PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2G_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2H_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2I_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4B_L5PHIA,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC22n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2J_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2K_L5PHIC,
const AllStubMemory<BARREL2S>& AS_L4PHICn5,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2L_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4D_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4E_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4F_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4C_L5PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4G_L5PHIC,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2B_L4PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4C_L5PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L4PHIA,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L4PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L5L6B_L4PHIB,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L1L2B_L3PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA3n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC23n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2D_L4PHIB,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB11n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA6n1,
const AllStubMemory<BARREL2S>& AS_L5PHICn3,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L1L2D_L3PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB10n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA4n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB9n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB14n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2F_L5PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2G_L5PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB15n1,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L5L6A_L3PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC21n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4B_L5PHIB,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2C_L5PHIB,
const AllStubMemory<BARREL2S>& AS_L6PHICn4,
const TrackletProjectionMemory<BARRELPS>& TPROJ_L5L6C_L3PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC23n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L3L4B_L6PHIA,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIB11n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIA6n1,
const VMStubMEMemory<BARREL2S>& VMSME_L6PHIA1n1,
const VMStubMEMemory<BARRELPS>& VMSME_L3PHIB12n1,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIB10n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIC24n1,
const TrackletProjectionMemory<BARREL2S>& TPROJ_L1L2H_L6PHIB,
const VMStubMEMemory<BARREL2S>& VMSME_L5PHIC19n1,
const VMStubMEMemory<BARREL2S>& VMSME_L4PHIA7n1,
const AllStubMemory<BARREL2S>& AS_L6PHIAn3,
BXType& bx_o,
FullMatchMemory<BARREL>& FM_L3L4_L5PHIB,
FullMatchMemory<BARREL>& FM_L5L6_L4PHIB,
FullMatchMemory<BARREL>& FM_L3L4_L5PHIC,
FullMatchMemory<BARREL>& FM_L1L2_L4PHIC,
FullMatchMemory<BARREL>& FM_L3L4_L6PHIA,
FullMatchMemory<BARREL>& FM_L5L6_L4PHIC,
FullMatchMemory<BARREL>& FM_L3L4_L6PHIB,
FullMatchMemory<BARREL>& FM_L3L4_L6PHIC,
FullMatchMemory<BARREL>& FM_L1L2_L6PHIA,
FullMatchMemory<BARREL>& FM_L1L2_L6PHIB,
FullMatchMemory<BARREL>& FM_L1L2_L6PHIC,
FullMatchMemory<BARREL>& FM_L1L2_L5PHIB,
FullMatchMemory<BARREL>& FM_L3L4_L5PHIA,
FullMatchMemory<BARREL>& FM_L5L6_L3PHIB,
FullMatchMemory<BARREL>& FM_L1L2_L5PHIC,
FullMatchMemory<BARREL>& FM_L1L2_L5PHIA,
FullMatchMemory<BARREL>& FM_L5L6_L4PHIA,
FullMatchMemory<BARREL>& FM_L1L2_L3PHIB,
FullMatchMemory<BARREL>& FM_L1L2_L4PHIA,
FullMatchMemory<BARREL>& FM_L1L2_L4PHIB);

#endif
